version: '3'
services:
    scrapy:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - "./ukcavegis:/usr/src/app/ukcavegis"
            - "./data:/usr/src/app/data"
        restart: always
